### ISSUE TITLE
Resulting DLL doesn't have any exports and is therefore not detected as valid OBS plugin

### ISSUE THREAD

**Issue by YorVeX** [kostya9/DotnetObsPluginWithNativeAOT#1]
Thanks for your work in this area, unfortunately I can't produce a valid OBS plugin from it.

I downloaded the solution here and opened it in Visual Studio Community 2022, then let it fetch the dependency via nuget. I tried both compiling it from VS and through the dotnet publish command from your blog post.

It compiles without errors and creates all the files in the /publish folder as expected, but the resulting DotnetObsPluginWithNativeAOT.dll doesn't have any exports when checked with the nirsoft DLL exports viewer:
![image](https://user-images.githubusercontent.com/528974/211179193-c94980e6-013e-4122-9e93-910601b1e128.png)

As a comparison, this is what the included obs-filters.dll plugin looks like when opened in that tool:
![image](https://user-images.githubusercontent.com/528974/211179277-1584c6a1-b040-47b4-84d5-8a79bd2bcae9.png)

As expected the OBS log then only says:
`Skipping module '../../obs-plugins/64bit/DotnetObsPluginWithNativeAOT.dll', not an OBS plugin`

Any ideas what I could try to solve this?

**Comment by YorVeX** [comment]
Unfortunately I am also unable to compile the NetObsBindings library myself, the script commands fail with a lot of these errors (whether I use those from the blog post or from generate_bindings.ps1):
```
Diagnostics for '.\obs-studio\libobs\obs-module.h':
    .\obs-studio\libobs/obs.h:95:1: error: unknown type name 'EXPORT'
    .\obs-studio\libobs/obs.h:98:1: error: unknown type name 'EXPORT'
    .\obs-studio\libobs/obs.h:101:1: error: unknown type name 'EXPORT'
    .\obs-studio\libobs/obs.h:104:1: error: unknown type name 'EXPORT'
    .\obs-studio\libobs/obs.h:107:1: error: unknown type name 'EXPORT'
    .\obs-studio\libobs/obs.h:140:1: error: unknown type name 'EXPORT'
    .\obs-studio\libobs/obs.h:144:15: error: unknown type name 'obs_module_t'
    .\obs-studio\libobs/obs.h:172:1: error: unknown type name 'EXPORT'
    .\obs-studio\libobs/obs.h:175:1: error: unknown type name 'EXPORT'
    .\obs-studio\libobs/obs.h:95:1: error: unknown type name 'EXPORT'
    .\obs-studio\libobs/obs.h:98:1: error: unknown type name 'EXPORT'
    .\obs-studio\libobs/obs.h:101:1: error: unknown type name 'EXPORT'
    .\obs-studio\libobs/obs.h:104:1: error: unknown type name 'EXPORT'
    .\obs-studio\libobs/obs.h:107:1: error: unknown type name 'EXPORT'
    .\obs-studio\libobs/obs.h:140:1: error: unknown type name 'EXPORT'
    .\obs-studio\libobs/obs.h:144:15: error: unknown type name 'obs_module_t'
    .\obs-studio\libobs/obs.h:172:1: error: unknown type name 'EXPORT'
    .\obs-studio\libobs/obs.h:175:1: error: unknown type name 'EXPORT'
Skipping '.\obs-studio\libobs\obs-module.h' due to one or more errors listed above.
```
Tried both with the current OBS master and the 27.2 branch with the same result.

**Comment by kostya9** [comment]
Thanks for checking out this project!

The exports were missing because I forgot to add NativeAOT section to the project file, fixed that, please try again with the latest code.

The output of the compilation will be in the native folder (e.g. for me bin\Release\net7.0\win-x64\native)

**Comment by kostya9** [comment]
Regarding the second question, I regenerated the bindings and didn't have these errors in the output. Maybe we have different versions of clang/clangsharp installed?

Could you check with these commands?
```
ClangSharpPInvokeGenerator -v
clang -v
```

For reference, my output is the following:
```
S D:\CloudRepos\Git\NetObsBindings> ClangSharpPInvokeGenerator -v
ClangSharp P/Invoke Binding Generator version 14.0.0
  clang version 14.0.0
  clangsharp version 14.0.0
PS D:\CloudRepos\Git\NetObsBindings> clang -v
clang version 14.0.6
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
PS D:\CloudRepos\Git\NetObsBindings
```

**Comment by YorVeX** [comment]
Thanks for the quick response!

In your blog post you specifically use the switch --version 13.0.0-beta1 when installing ClangSharpPInvokeGenerator and --version 13.0.0 for LLVM. I know that's outdated but I thought I had the best chances for success when going with the same version that you used. My other option would have been to go with the latest version which I believe is 15? I don't see how I could have possibly ended up with version 14 😆 

Unsurprisingly the version check command says 13, though your second command comes up with an error. I never installed anything for clang before, only followed what is in your blog post.
![image](https://user-images.githubusercontent.com/528974/211205003-e168bcfa-4cb0-4f80-9dc0-da8dee0e0e83.png)

**Comment by YorVeX** [comment]
![image](https://user-images.githubusercontent.com/528974/211205605-a68665cd-fbd7-4d91-983d-8c9ae2fbf6d9.png)
updated to version 15 now and will try with your latest project file

**Comment by YorVeX** [comment]
Still getting the same error messages when trying to build the NetObsBindings library, maybe because I am missing clang components?

**Comment by YorVeX** [comment]
The good news is that with your changed project file for DotnetObsPluginWithNativeAOT now indeed I get the exports and OBS loads the module and shows the log messages produced by it. Thanks again!

I work mostly with C#, my C++ knowledge is limited and old and I only need a rather small functionality so with NativeAOT I was hoping to be able to cut some corners and do it in C#. Years ago OBS classic had [a CLR host plugin](https://obsproject.com/forum/resources/clr-host-plugin.21/) but OBS Studio doesn't, maybe that's something which could also be achieved with NativeAOT.

The only thing that is not so elegant about this solution is having to clutter the OBS plugins folder with 186 additional files from the publish folder, a lot of which are DLLs that OBS tries to load on every startup before it finds they aren't valid OBS plugins, increasing startup time and spamming the OBS logs with messages for each of them:
![image](https://user-images.githubusercontent.com/528974/211206714-7c2573c7-7c4b-4728-b865-a7cab09dd7a2.png)

On the upside out of this I now get the full power of the .NET framework including things like XML or JSON parsing and network connectivity etc.

**Comment by kostya9** [comment]
@YorVeX I have only 2 files in my publish folder, maybe those 100+ files are from the previous attempts? AFAIK NativeAot produces self-contained DLL which doesn't need that stuff.

**Comment by kostya9** [comment]
I was trying to repro the bindings generation issue on my other machine.

I think it's related that LLVM doesn't add itself to PATH. You can try adding clang to PATH (C:\Program Files\LLVM\lib, C:\Program Files\LLVM\bin).

The generation worked with: LLVM 15 (the same as your), ClangSharpGenerator 14.0.0-rc1 (I tried with 15, but bumped into this issue https://github.com/dotnet/ClangSharp/issues/413), Visual Studio Desktop C++ tools.

**Comment by kostya9** [comment]
> Years ago OBS classic had [a CLR host plugin](https://obsproject.com/forum/resources/clr-host-plugin.21/) but OBS Studio doesn't, maybe that's something which could also be achieved with NativeAOT.

That's exactly why I was looking into this stuff 🙂

Previously I achieved something similar with DNNE (https://github.com/AaronRobinsonMSFT/DNNE), but it didn't support self-contained and I ran into the same issue as you with a bunch of files there. 

Fortunately, the NativeAOT solution is both functional and single-file.

**Comment by YorVeX** [comment]
> @YorVeX I have only 2 files in my publish folder, maybe those 100+ files are from the previous attempts? AFAIK NativeAot produces self-contained DLL which doesn't need that stuff.

Yes you are right, you get those 186 files in the publish folder when building the project without the PublishAot setting in the project file and of course even after I fixed this and rebuilt, this didn't remove those files from the previous attempt. I just deleted the folder and started over and now I only get the dll and the debug symbols file 👍

**Comment by YorVeX** [comment]
> I was trying to repro the bindings generation issue on my other machine.
> 
> I think it's related that LLVM doesn't add itself to PATH. You can try adding clang to PATH (C:\Program Files\LLVM\lib, C:\Program Files\LLVM\bin).
> 
> The generation worked with: LLVM 15 (the same as your), ClangSharpGenerator 14.0.0-rc1 (I tried with 15, but bumped into this issue [dotnet/ClangSharp#413](https://github.com/dotnet/ClangSharp/issues/413)), Visual Studio Desktop C++ tools.

Now running the same versions and added the LLVM bin directory to the system PATH, build still fails:
![image](https://user-images.githubusercontent.com/528974/211210961-56649316-7c44-48f5-8556-4fb5df5e34ba.png)
That's with the release/27.2 branch of OBS.


Against the latest master (using your build script to make sure I really get a fresh copy) I get those EXPORT related errors instead:
![image](https://user-images.githubusercontent.com/528974/211211157-d6d8c78a-3152-4881-b6c8-60977a7d3ac1.png)

**Comment by kostya9** [comment]
Ugh, that's unfortunate. Something ought to be wrong in how clang compiles the obs sources, but I am not sure what, as I am not very knowledgeable about the C toolchain too 😢

**Comment by kostya9** [comment]
If you need more OBS APIs added to the bindings, feel free to open an issue in the bindings repo

**Comment by YorVeX** [comment]
Thanks, will do. The original issue here is definitely solved so we can close this, thanks a lot for your help!
